baseurl:            /
exclude:            [
                        "css",
                        "_scss"
                    ]
keep_files:         [
                        "_site/edx-capa.css"
                    ]
